/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackgroundComponent: typeof import('./src/components/BackgroundComponent.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    LoadingComponent: typeof import('./src/components/LoadingComponent.vue')['default']
    MessageComponent: typeof import('./src/components/MessageComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongComponet: typeof import('./src/components/SongComponet.vue')['default']
    StatsComponent: typeof import('./src/components/StatsComponent.vue')['default']
    UserComponent: typeof import('./src/components/UserComponent.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
